// 자동 생성 파일입니다. tools/convert-ramen.ps1 실행 결과로 갱신됩니다. 직접 수정하지 마세요.
const RAMEN_SHOPS = [
    {
        "id":  "ramen-2",
        "city":  "yokohama",
        "nameKo":  "요시무라야",
        "nameJa":  "吉村家",
        "genre":  "백탕/이에케",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "이에케 원조 본점, 요코하마역 도보 8분",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.4630187,139.6150749",
        "station":  "요코하마역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.4630187,
        "lng":  139.6150749
    },
    {
        "id":  "ramen-3",
        "city":  "yokohama",
        "nameKo":  "스기타야",
        "nameJa":  "杉田家",
        "genre":  "백탕/이에케",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "요시무라야 직계 1호점, 신스기타역 도보 3분",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.3881631,139.6182152",
        "station":  "신스기타역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.3881631,
        "lng":  139.6182152
    },
    {
        "id":  "ramen-4",
        "city":  "yokohama",
        "nameKo":  "스미레 요코하마점",
        "nameJa":  "すみれ 横浜店",
        "genre":  "백탕/미소",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "본점은 삿포로, 노게/사쿠라기초 지역",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.4479278,139.6307316",
        "station":  "사쿠라기초역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.4479278,
        "lng":  139.6307316
    },
    {
        "id":  "ramen-5",
        "city":  "yokohama",
        "nameKo":  "라멘 지로 요코하마 칸나이점",
        "nameJa":  "ラーメン二郎 横浜関内店",
        "genre":  "백탕/지로계",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "본점은 도쿄 미타, 칸나이역 도보",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.4419684,139.6307759",
        "station":  "칸나이역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.4419684,
        "lng":  139.6307759
    },
    {
        "id":  "ramen-6",
        "city":  "tokyo",
        "nameKo":  "아오시마 쇼쿠도",
        "nameJa":  "青島食堂 秋葉原店",
        "genre":  "백탕/쇼유",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "아키하바라점 주소 확인 완료(千代田区神田佐久間町3-20-1)",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6974587,139.7788427",
        "station":  "아키하바라역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6974587,
        "lng":  139.7788427
    },
    {
        "id":  "ramen-7",
        "city":  "tokyo",
        "nameKo":  "무기나에",
        "nameJa":  "麦苗",
        "genre":  "청탕",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.5907765,139.7328034",
        "station":  "미나미오이",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.5907765,
        "lng":  139.7328034
    },
    {
        "id":  "ramen-8",
        "city":  "tokyo",
        "nameKo":  "호타테 비요리",
        "nameJa":  "ホタテ日和",
        "genre":  "청탕/가리비츠케멘",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "정리권제 운영(SNS 공지 확인 필요)",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6985564,139.7771593",
        "station":  "아사쿠사바시역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6985564,
        "lng":  139.7771593
    },
    {
        "id":  "ramen-9",
        "city":  "tokyo",
        "nameKo":  "라멘야 시마",
        "nameJa":  "らぁ麺 嶋",
        "genre":  "청탕/백간장",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "완전예약제(전날 오전8시 온라인예약)",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6883441,139.6808875",
        "station":  "니시신주쿠",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6883441,
        "lng":  139.6808875
    },
    {
        "id":  "ramen-10",
        "city":  "yokohama",
        "nameKo":  "시나소바야",
        "nameJa":  "支那そばや",
        "genre":  "정통 라멘",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "1986년 창업 본점, 요코하마 토츠카구 확인 완료(주소: 戸塚区戸塚町4081-1, 사노 미노루 대표), 토츠카역 도보 5분",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.4014011,139.5318251",
        "station":  "토츠카역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.4014011,
        "lng":  139.5318251
    },
    {
        "id":  "ramen-11",
        "city":  "tokyo",
        "nameKo":  "테우치 렌",
        "nameJa":  "手打ち 蓮",
        "genre":  "청탕",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "스미다구 키쿠카와 지역",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6914545,139.7959078",
        "station":  "키쿠카와역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6914545,
        "lng":  139.7959078
    },
    {
        "id":  "ramen-12",
        "city":  "tokyo",
        "nameKo":  "라멘 히스이",
        "nameJa":  "ラーメン翡翠",
        "genre":  "청탕/조개시오",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "아카사카, 라멘 브레이크비츠 계열 스핀오프",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6738629,139.7373808",
        "station":  "아카사카역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6738629,
        "lng":  139.7373808
    },
    {
        "id":  "ramen-13",
        "city":  "tokyo",
        "nameKo":  "시부야 카짱라멘",
        "nameJa":  "渋谷かっちゃんラーメン",
        "genre":  "찬계라멘",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "시부야 사쿠라 스테이지 1층, 24시간 영업",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6561968,139.7023617",
        "station":  "시부야역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6561968,
        "lng":  139.7023617
    },
    {
        "id":  "ramen-14",
        "city":  "tokyo",
        "nameKo":  "스파이스라멘 텐토센 시모키타자와점",
        "nameJa":  "スパイスラーメン 点と線.下北沢店",
        "genre":  "스파이스백탕",
        "priceRange":  "미기록",
        "capacity":  "1-2인",
        "waiting":  "",
        "seatType":  "",
        "saltiness":  null,
        "richness":  null,
        "recommendedMenu":  "",
        "comment":  "",
        "otakuTip":  "로지우라 카레 사무라이 계열 스파이스라멘",
        "orderPayment":  "",
        "hours":  "",
        "lastVisited":  "",
        "mapUrl":  "https://www.google.com/maps?q=35.6648005,139.6660945",
        "station":  "시모키타자와역",
        "recommenderNickname":  null,
        "showNickname":  false,
        "lat":  35.6648005,
        "lng":  139.6660945
    }
];
